Progress records: <br />

<?php
$columnSet = $this->inbox['columnSet'];
$recordSet = $this->inbox['recordSet'];
?>
<table>
  <tr>
    <?php foreach ($columnSet as $column): ?>
      <th><?php echo $this->escape($column); ?></th>
    <?php endforeach; ?>
  </tr>

  <?php foreach ($recordSet as $record): ?>
    <tr>
      <td><?php echo $this->escape($record->id) ?></td>
      <td><?php echo $this->escape($record->eid) ?></td>
      <td><?php echo $this->escape($record->uid) ?></td>
      <td><?php echo $this->escape($record->week) ?></td>
      <td><?php echo $this->escape($record->weight) ?></td>
    </tr>
  <?php endforeach ?>

</table>